### PR TITLE
Update Localizable.strings

### PR DESCRIPTION
**Pull request by raspingbard**
I improved some of the English strings slightly.

### CODE REVIEW

**Comment by raspingbard** [comment]
On your Settings strings: Some use Headline capitalization like "Low Thread Priority", while others using Sentence capitalization like "Display coordinate labels".  This should be consistent.  Would you like me to fix this for you?  Which way to you like?

**Comment by new3Rs** [comment]
Nice modifications!

If it is not a sentence, I prefer "Low Thread Priority"-like.

Thank you for your cooperation!

**Comment by raspingbard** [comment]
In the Settings UI, some labels are half-sentences, like "Display coordinate labels" and "Display Winrate", so I wouldn't know how to change some and not others.

But in the Start UI, all the labels use sentence capitalization, like "Komi", "Handicap stones", "Time per move", and "Battery saving".  I think this consistency is good.

In the Settings UI, I would recommend capitalizing headers like "Game Mode Settings", but using sentence capitalization on the individual settings, like "Display winrate".  It's your decision.

**Comment by new3Rs** [comment]
Thank you, @raspingbard san!

I will decide them when I import your pull request into next version.

**Comment by raspingbard** [comment]
Not sure what you mean.  Do you want me to make the changes to my branch, or wait until later?

**Comment by new3Rs** [comment]
I will explain what I am thinking.

In general,
When UIs are buttons, they are triggers for action. So I think that sentences are suitable for their explanations.
When UIs are not buttons (such as select, switch, and field), they are kind of options. So I think that nouns are suitable for their explanations.

So I think that it will be more consistent if we find noun expressions for items such as "Display coordinate labels" in Setting menus.

I will decide what I should do when I merge your latest pull request at that time.
You do not need to wait for what I will do.

Thank you!

**Comment by raspingbard** [comment]
new3Rs san, I was planning to make suggested changes to the Settings UI, but I've been too busy.  When I do, should I use this same Pull Request, or create another one?

**Comment by new3Rs** [comment]
@raspingbard san,

Thank you for your cooperation!

Since this pull request was merged, you can create another one.

**Comment by new3Rs** [comment]
@raspingbard san,

Your contributions are included in the version 3.10.0.
Thank you!

**Pull request merged**
